# Generated by Django 4.1.4 on 2023-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
